<a href="https://colab.research.google.com/github/vunnampragathi/pragathi_data_606/blob/main/src/draft_proposal_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
data = pd.read_csv("/content/train_1.csv.zip")

In [ ]:
data

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
0,2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
1,2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
2,3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
3,4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Underworld_(serie_de_películas)_es.wikipedia.o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.0,12.0,13.0,3.0,5.0,10.0
145059,Resident_Evil:_Capítulo_Final_es.wikipedia.org...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145060,Enamorándome_de_Ramón_es.wikipedia.org_all-acc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145061,Hasta_el_último_hombre_es.wikipedia.org_all-ac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145062,Francisco_el_matemático_(serie_de_televisión_d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.shape

(145063, 551)

In [ ]:
data.info

<bound method DataFrame.info of                                                      Page  2015-07-01  \
0                 2NE1_zh.wikipedia.org_all-access_spider        18.0
1                  2PM_zh.wikipedia.org_all-access_spider        11.0
2                   3C_zh.wikipedia.org_all-access_spider         1.0
3              4minute_zh.wikipedia.org_all-access_spider        35.0
4       52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...         NaN
...                                                   ...         ...
145058  Underworld_(serie_de_películas)_es.wikipedia.o...         NaN
145059  Resident_Evil:_Capítulo_Final_es.wikipedia.org...         NaN
145060  Enamorándome_de_Ramón_es.wikipedia.org_all-acc...         NaN
145061  Hasta_el_último_hombre_es.wikipedia.org_all-ac...         NaN
145062  Francisco_el_matemático_(serie_de_televisión_d...         NaN

        2015-07-02  2015-07-03  2015-07-04  2015-07-05  2015-07-06  \
0             11.0         5.0        13.0        14.0         9.0
1             14.0        15.0        18.0        11.0        13.0
2              0.0         1.0         1.0         0.0         4.0
3             13.0        10.0        94.0         4.0        26.0
4              NaN         NaN         NaN         NaN         NaN
...            ...         ...         ...         ...         ...
145058         NaN         NaN         NaN         NaN         NaN
145059         NaN         NaN         NaN         NaN         NaN
145060         NaN         NaN         NaN         NaN         NaN
145061         NaN         NaN         NaN         NaN         NaN
145062         NaN         NaN         NaN         NaN         NaN

        2015-07-07  2015-07-08  2015-07-09  ...  2016-12-22  2016-12-23  \
0              9.0        22.0        26.0  ...        32.0        63.0
1             22.0        11.0        10.0  ...        17.0        42.0
2              0.0         3.0         4.0  ...         3.0         1.0
3             14.0         9.0        11.0  ...        32.0        10.0
4              NaN         NaN         NaN  ...        48.0         9.0
...            ...         ...         ...  ...         ...         ...
145058         NaN         NaN         NaN  ...         NaN         NaN
145059         NaN         NaN         NaN  ...         NaN         NaN
145060         NaN         NaN         NaN  ...         NaN         NaN
145061         NaN         NaN         NaN  ...         NaN         NaN
145062         NaN         NaN         NaN  ...         NaN         NaN

        2016-12-24  2016-12-25  2016-12-26  2016-12-27  2016-12-28  \
0             15.0        26.0        14.0        20.0        22.0
1             28.0        15.0         9.0        30.0        52.0
2              1.0         7.0         4.0         4.0         6.0
3             26.0        27.0        16.0        11.0        17.0
4             25.0        13.0         3.0        11.0        27.0
...            ...         ...         ...         ...         ...
145058         NaN         NaN        13.0        12.0        13.0
145059         NaN         NaN         NaN         NaN         NaN
145060         NaN         NaN         NaN         NaN         NaN
145061         NaN         NaN         NaN         NaN         NaN
145062         NaN         NaN         NaN         NaN         NaN

        2016-12-29  2016-12-30  2016-12-31
0             19.0        18.0        20.0
1             45.0        26.0        20.0
2              3.0         4.0        17.0
3             19.0        10.0        11.0
4             13.0        36.0        10.0
...            ...         ...         ...
145058         3.0         5.0        10.0
145059         NaN         NaN         NaN
145060         NaN         NaN         NaN
145061         NaN         NaN         NaN
145062         NaN         NaN         NaN

[145063 rows x 551 columns]>

In [ ]:
data.dtypes

Page           object
2015-07-01    float64
2015-07-02    float64
2015-07-03    float64
2015-07-04    float64
               ...
2016-12-27    float64
2016-12-28    float64
2016-12-29    float64
2016-12-30    float64
2016-12-31    float64
Length: 551, dtype: object

In [ ]:
df=data.dropna()

In [ ]:
df.shape

(117277, 551)

In [ ]:
data_start_date = df.columns[1]
data_end_date = df.columns[-1]
print('Data ranges from %s to %s' % (data_start_date, data_end_date))

Data ranges from 2015-07-01 to 2016-12-31